[build]
  base = "Frontend"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/req/*"
  to = "https://library-management-system-client-1.onrender.com/req/:splat"
  status = 200
  force = true

[functions]
  directory = "netlify/functions"